<html>
    <head>
        <title>Stop Wage Theft | Methodology</title>
        <?php include '../includes/head_meta.php'; ?>
    </head>
    <body class="home">
        <div id="wrapper">
            <header id="header">
                <h2 id="title"><a href="/">Stop Wage Theft</a></h2>
                <?php include '../includes/navigation.php'; ?>
            </header>
            <section id="content">
                <div class="content-section">
                    <h1>Methodology</h1>
                    <p>Informally we are simply the Wage Theft Group. The core value that brings us to volunteer is a desire to do social good. In the Silicon Valley culture of corporate technology, social good is too often a veneered banner that misses the substance of the idea. The Wage Theft Group is a place where business decisions are left at the door.</p>
                    <p>The group members change; they contribute what they can when they can. The composition of the group is a mix of data scientists, product designers, and subject matter experts. At CIFE, Martin Fischer the Director of CIFE and Marc Ramsey a research software developer provide administrative and conceptual support. There are people like Ash Chakraborty, a data scientist with a background in machine learning; Ash immigrated to the U.S. to attend Minnesota State and then nearly froze driving from Minnesota to his first job in California. There is Brian Spiering, a visiting faculty member at GalvanizeU in San Francisco; like Ash he is also a data scientist with a background in machine learning. Brian has a focus on projects with a social consciousness and brings to the group his mentoring skills as a teacher.  We have Thor Lee a product developer with an eye for visualizations and the user experience. A pair of data scientists with a background is physics are Matt Giguere and Michael Myers. We have members like Kathleen Tang, who is helping her parents start a Thai catering business between completing her data science degree and volunteering with socially conscious projects. We have from the Stanford Statistics department Ting-Po and Kris Sankaran. From the Stanford Sustainable Design and Construction program graduate student Chris Pickard has joined the group; last summer Chris and Forest worked together with Dan Smith at the Roofers Union on developing a wage theft app that unfortunately was shelved due to business type concerns. Rounding out the group we have our subject matter experts Ruth Silver-Taube and Michael Tayag from the Wage Theft Coalition, Michael Eastwood from the Department of Labor Wage and Hour Division, and Arturo Sainz from the Foundation for Fair Contracting. These subject matter experts are our steering committee that keeps us on track and provides feedback.</p>
                    <p><strong>Problem:</strong> There are problems with using current technologies for the social good. While we recognize there are companies attempting to develop socially good technology, we have seen a troubling pattern. Although the root cause is not clear, we have identified two: </p>
                    <p>First, developers are afraid to pursue genuinely useful digital tools – they think they will lose their venture capital funding. This was the case for two startups with which we collaborated that initially pursued socially good technology but abruptly stopped.</p>
                    <p>Second, there is a failure to recognize the very real concerns of the workers. In a panic to generate sales, one startup used ambiguity in the law to justify the inclusion of features in its app that subvert worker privacy. As a result, there are currently no technologies that adequately address the wage needs of workers. Moreover, developers are creating digital tools for companies to monitor workers, without developing equivalent tools for the workers to document the work they actually performed. This imbalance could easily lead to increased exploitation of the workforce.</p>
                    <p><strong>Hypothesis:</strong> We begin with the ideal that an ability for workers to organize, securely communicate, and access information about their employer is integral to their ability to address issues like wage theft, unsafe working conditions, and environmental exploitation – digital tools are a way to keep employers in check.</p>
<p><strong>Research Questions:</strong> We want to understand characteristics of technologies that are detrimental to users, as well as to develop technologies that enhance social good. Three questions guide us:</p>
<ul>
    <li>With our primary questions that lead to finding which predictive models support understanding about both specific employers and industries?</li>
    <li>We then ask to what degree do visualizations of impact estimates allow advocates to A) draw conclusions and B) host discussions. We want to know:</li>
    <ul>
        <li>To what degree is organizing with colleagues supported?</li>
        <li>What gives workers trust that their communications and ubiquitous presence are private and secure?</li>
    </ul>
</ul>
<p><strong>Methods:</strong> We use Community-based Participatory Research combined with an ethnography. The CBPR is a multi-disciplinary approach; we are engineering, data science, and law, participating with regional government and twenty-four community groups. We have wage theft as an experiment platform. To quantify, predict, and visualize wage theft, we have three pragmatic questions: A) framework, what features represent the context; B) formalization, how do these features relate to predict; and C) method, who uses the digital tools. Through ethnography, we gain the knowledge to solve these pragmatic questions. We use bootstrapping of existing apps and hardware as a method to iterate development. This takes our focus off the nuances of app development. As an evaluation metric, we measure the pragmatic uptake by individuals in the workforce, community education, enforcement groups, and policy makers.</p>
<p><strong>Discussion:</strong> When we achieve our goals, then we have moderated socially questionable technology. In this manner, we will have developed a hypothesis about technology features that support social good and will have validated it as a theory. As a CBPR, we will have walked a balance between theory and practical contribution: On policy, our outputs will support an enactment of anti-wage theft policies and ordinances leveraging the purchasing power of local government, permitting, and licensing. We will have developed a ubiquitous system that pulls data, processes that data, forms predictions, and then gives that data to both the workforce and advocacy groups as both abstracted visualizations and as specific data on their employer. We intend to utilize these data and visualizations as a powerful organizing tool. Throughout the process, we must ensure the privacy of the workers; we protect privacy by collaborating with a law clinic with attorney-client privilege. While attorney-client privilege provides necessary privacy protection, we look for an ubiquitous privacy solution. For hypothesis development, we have worked with the Santa Clara County Wage Theft Coalition and the Foundation for Fair Contracting. We are uniquely positioned to understand a workers’ needs for specific technology. Our strength is that we educate and inform policy makers in the Silicon Valley who enact local ordinances – we have an opportunity to expand to the State level. To teach the importance of workers’ use of digital tools for these purposes, we are piloting an education program to include worker protection technology in the workforce’s vocational education.</p>
<p><strong>Conclusion:</strong> Our research will result in an infusion of digital tools into the Silicon Valley community. We will pilot digital tools that support organizing, with secure communications, and information about employers that commit wage theft. We expect a validated uptake in three industries (home healthcare, restaurant, and construction). We have the potential for an impact on the United States’ $22-50 billion per year wage theft problem, where, enforcement relies on understaffed agencies and disseminating printed information. We will demonstrate that the theory we validate on the wage theft platform transfers to the larger struggle against the denial of workers’ rights.</p>
                </div>
            </section>
        </div>
        <?php include '../includes/footer.php'; ?>
    </body>
</html>
